language: node_js

node_js:
  - 'node'
  - '12'
  - '10'

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

branches:
  only:
  - master
  - /^release-.*/

install:
  - npm uninstall typescript --no-save
  - npm install codecov -g
  - npm install

after_success:
  - pip install --user codecov
  - codecov --file coverage/lcov.info --disable search

git:
  depth: 1