language: node_js

node_js:
  - 'node'
  - '12'
  - '10'

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

branches:
  only:
  - master
  - /^release-.*/

install:
  - npm uninstall typescript --no-save
  - npm install istanbul
  - npm install

after_success:
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1